version: 2.1

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - build
            - lint

jobs:
  install_dependencies:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install NPM modules
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
  build:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: npm run build
      - run:
          name: Create Archive
          command: zip -r build.zip build
      - store_artifacts:
          path: build.zip
          destination: build.zip
  lint:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Lint
          command: npm run lint
  deploy:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - run:
          name: Nothing yet
          command: echo Nothing here yet
