version: 2.1

workflows:
  build_and_deploy:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      # normally, lint & build could go in parallel, but build has to finish after lint or deploy will fail
      # the deploy job requires that the build job be the most recent run
      - build:
          requires:
            - lint
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "yarn.lock" }}
          - v2-dependencies-
      - run:
          name: Install NPM modules
          command: yarn --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: "."
          paths:
            - node_modules
  lint:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  build:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn build
      - run:
          name: Create Archive
          command: zip -r build.zip build
      - store_artifacts:
          path: build.zip
          destination: build.zip
  deploy:
    docker:
      - image: cimg/node:12.18
    steps:
      - run:
          name: Deploy to web server
          command: curl https://csclub.cs.iupui.edu/hooks/deploy.php
